# Generated by Django 5.2.3 on 2025-06-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameramen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.TextField()),
                ('event_description', models.TextField()),
                ('event_date', models.DateField()),
                ('location', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cameramen', models.ManyToManyField(related_name='events_cameramens', to='cameramen.cameramen')),
            ],
        ),
    ]
