# Generated by Django 5.2.3 on 2025-06-24 17:22

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_events_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='price',
        ),
        migrations.AddField(
            model_name='events',
            name='user',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, related_name='event', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
