# Generated by Django 5.2.3 on 2025-07-02 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_events_price_events_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
