# Generated by Django 5.2.3 on 2025-06-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cameramen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('cameramen_mobile_no', models.IntegerField()),
                ('skills', models.CharField(choices=[('cinimatography', 'cinimatography'), ('videography', 'videography'), ('drowner', 'drowner')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
