# Generated by Django 5.2.3 on 2025-06-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField()),
                ('mobile_no', models.IntegerField()),
                ('address', models.TextField()),
                ('order_type', models.TextField()),
                ('order_description', models.TextField()),
                ('total_price', models.IntegerField()),
                ('price_paid', models.IntegerField()),
                ('pending_payment', models.IntegerField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
