# Generated by Django 5.2.3 on 2025-06-16 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='pending_payment',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='price_paid',
        ),
    ]
