# Generated by Django 5.2.3 on 2025-06-16 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_customer_pending_payment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='date_time',
            new_name='created_at',
        ),
    ]
