# Generated by Django 5.2.3 on 2025-07-02 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_customer_paid_amount_customer_pending_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='paid_amount',
            new_name='paid_price',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='pending_amount',
        ),
    ]
