# Generated by Django 5.2.3 on 2025-07-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_rename_paid_amount_customer_paid_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='paid_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='total_price',
            field=models.IntegerField(),
        ),
    ]
